"""change in document check for processing status

Revision ID: 026b575b525b
Revises: 9a8b54dd42a4
Create Date: 2026-02-24 15:20:55.990876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "026b575b525b"
down_revision: Union[str, Sequence[str], None] = "9a8b54dd42a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("processing_status", sa.String(length=15), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "processing_status")
    # ### end Alembic commands ###
