"""after merge sepcilalization

Revision ID: 0bbf8b9a99c8
Revises: 64b80b92e885
Create Date: 2026-03-12 05:53:39.099956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bbf8b9a99c8"
down_revision: Union[str, Sequence[str], None] = "64b80b92e885"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialisations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_specialisations_id"), "specialisations", ["id"], unique=False
    )
    op.add_column("agents", sa.Column("specialisation_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_agents_specialisation"), table_name="agents")
    op.create_index(
        op.f("ix_agents_specialisation_id"),
        "agents",
        ["specialisation_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "agents", "specialisations", ["specialisation_id"], ["id"]
    )
    op.drop_column("agents", "specialisation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "specialisation",
            postgresql.ENUM(
                "GENERAL", "HR", "TECHNICAL_SUPPORT", name="agent_specialisation"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "agents", type_="foreignkey")
    op.drop_index(op.f("ix_agents_specialisation_id"), table_name="agents")
    op.create_index(
        op.f("ix_agents_specialisation"), "agents", ["specialisation"], unique=False
    )
    op.drop_column("agents", "specialisation_id")
    op.drop_index(op.f("ix_specialisations_id"), table_name="specialisations")
    op.drop_table("specialisations")
    # ### end Alembic commands ###
