"""change in agent model for access

Revision ID: 14de38cbf92b
Revises: 547c7dbaa7cf
Create Date: 2026-02-23 19:18:31.969954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "14de38cbf92b"
down_revision: Union[str, Sequence[str], None] = "547c7dbaa7cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("is_public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "is_public")
    # ### end Alembic commands ###
