"""change in tenant  model for link

Revision ID: 17394a8c3c33
Revises: f00fa1e5b9be
Create Date: 2026-02-24 10:49:38.121696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "17394a8c3c33"
down_revision: Union[str, Sequence[str], None] = "f00fa1e5b9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tenants_created_by_fkey"), "tenants", type_="foreignkey")
    op.drop_column("tenants", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("tenants_created_by_fkey"), "tenants", "users", ["created_by"], ["id"]
    )
    # ### end Alembic commands ###
