"""add agent name, tenant name user name in user_log

Revision ID: 1a9d3b7ce655
Revises: 15a4128c021f
Create Date: 2026-03-05 08:55:40.949228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1a9d3b7ce655"
down_revision: Union[str, Sequence[str], None] = "15a4128c021f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_logs", sa.Column("tenant_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "usage_logs", sa.Column("user_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "usage_logs", sa.Column("agent_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "usage_logs", sa.Column("agent_category", sa.String(length=255), nullable=False)
    )
    op.create_index(
        op.f("ix_usage_logs_agent_category"),
        "usage_logs",
        ["agent_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_logs_agent_name"), "usage_logs", ["agent_name"], unique=False
    )
    op.create_index(
        op.f("ix_usage_logs_tenant_name"), "usage_logs", ["tenant_name"], unique=False
    )
    op.create_index(
        op.f("ix_usage_logs_user_name"), "usage_logs", ["user_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_logs_user_name"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_tenant_name"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_agent_name"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_agent_category"), table_name="usage_logs")
    op.drop_column("usage_logs", "agent_category")
    op.drop_column("usage_logs", "agent_name")
    op.drop_column("usage_logs", "user_name")
    op.drop_column("usage_logs", "tenant_name")
    # ### end Alembic commands ###
