"""change in document check change doc for filename

Revision ID: 31505ce0a964
Revises: d96e56d41990
Create Date: 2026-02-24 16:45:15.006392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "31505ce0a964"
down_revision: Union[str, Sequence[str], None] = "d96e56d41990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_name")
    # ### end Alembic commands ###
