"""update the daily uage summary for some columns

Revision ID: 38b6925bed9a
Revises: 9e0868cece2a
Create Date: 2026-02-27 14:12:44.389957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "38b6925bed9a"
down_revision: Union[str, Sequence[str], None] = "9e0868cece2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
