"""after merge of session_id and user_id logic

Revision ID: 3a3bec68f8b9
Revises: 466a7ca2ff60
Create Date: 2026-03-05 07:17:50.555783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a3bec68f8b9"
down_revision: Union[str, Sequence[str], None] = "466a7ca2ff60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_constraint(
        op.f("conversations_user_id_fkey"), "conversations", type_="foreignkey"
    )
    op.drop_column("conversations", "user_id")
    op.alter_column(
        "usage_logs",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usage_logs",
        "user_id",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.add_column(
        "conversations",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("conversations_user_id_fkey"),
        "conversations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
