"""modify the conversation for session_id

Revision ID: 466a7ca2ff60
Revises: 75c27472ae86
Create Date: 2026-03-03 11:46:08.404149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "466a7ca2ff60"
down_revision: Union[str, Sequence[str], None] = "75c27472ae86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("session_id", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "conversations", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("ix_conversations_session_id"),
        "conversations",
        ["session_id"],
        unique=False,
    )
    op.add_column(
        "usage_logs", sa.Column("session_id", sa.String(length=255), nullable=False)
    )
    op.alter_column("usage_logs", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        op.f("ix_usage_logs_session_id"), "usage_logs", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_logs_session_id"), table_name="usage_logs")
    op.alter_column("usage_logs", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("usage_logs", "session_id")
    op.drop_index(op.f("ix_conversations_session_id"), table_name="conversations")
    op.alter_column(
        "conversations", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("conversations", "session_id")
    # ### end Alembic commands ###
