"""added theme_id in agent config table

Revision ID: 50c6233588e2
Revises: bb4bb6100a0a
Create Date: 2026-03-24 14:14:28.454496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c6233588e2'
down_revision: Union[str, Sequence[str], None] = 'bb4bb6100a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_configs', 'theme_config', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.drop_column('agent_configs', 'theme_id')
    # ### end Alembic commands ###
