"""change the User model

Revision ID: 547c7dbaa7cf
Revises: bd9ff332ed24
Create Date: 2026-02-23 16:49:44.421689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "547c7dbaa7cf"
down_revision: Union[str, Sequence[str], None] = "bd9ff332ed24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tenant_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tenant_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
