"""after merge

Revision ID: 64b80b92e885
Revises: 976b7b544571
Create Date: 2026-03-10 09:53:04.281523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "64b80b92e885"
down_revision: Union[str, Sequence[str], None] = "976b7b544571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_conversations_ended_at"), "conversations", ["ended_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_ended_at"), table_name="conversations")
    op.drop_column("conversations", "ended_at")
    # ### end Alembic commands ###
