"""after theme code merge

Revision ID: 74b10d9c28b1
Revises: 9d9a237bb403
Create Date: 2026-03-20 03:51:16.605789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "74b10d9c28b1"
down_revision: Union[str, Sequence[str], None] = "9d9a237bb403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("primary_color", sa.String(length=10), nullable=True),
        sa.Column("font_family", sa.String(length=50), nullable=True),
        sa.Column("widget_position", sa.String(length=20), nullable=True),
        sa.Column("widget_size", sa.String(length=20), nullable=True),
        sa.Column("widget_launcher_icon", sa.String(), nullable=True),
        sa.Column("bot_avatar", sa.String(), nullable=True),
        sa.Column("hide_estimated_wait_time", sa.Boolean(), nullable=True),
        sa.Column("disable_sound_notification", sa.Boolean(), nullable=True),
        sa.Column("hide_widget_when_offline", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_theme_config_id"), "theme_config", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_theme_config_id"), table_name="theme_config")
    op.drop_table("theme_config")
    # ### end Alembic commands ###
