"""modify the agent

Revision ID: 75c27472ae86
Revises: 663e895c0dc9
Create Date: 2026-03-03 04:25:19.024176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "75c27472ae86"
down_revision: Union[str, Sequence[str], None] = "663e895c0dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("is_chat_agent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "is_chat_agent")
    # ### end Alembic commands ###
