"""after marge allowed sources

Revision ID: 976b7b544571
Revises: b5bf475750f4
Create Date: 2026-03-06 10:38:48.019416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "976b7b544571"
down_revision: Union[str, Sequence[str], None] = "b5bf475750f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_configs",
        sa.Column("allowed_sources", sa.ARRAY(sa.String(length=100)), nullable=True),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("tenant_name", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("user_id", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("user_name", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("agent_name", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("agent_category", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "daily_usage_summary", sa.Column("total_requests", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_daily_usage_summary_agent_category"),
        "daily_usage_summary",
        ["agent_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_summary_agent_name"),
        "daily_usage_summary",
        ["agent_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_summary_tenant_name"),
        "daily_usage_summary",
        ["tenant_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_summary_user_id"),
        "daily_usage_summary",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_summary_user_name"),
        "daily_usage_summary",
        ["user_name"],
        unique=False,
    )
    op.alter_column(
        "documents", "category", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "category", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_index(
        op.f("ix_daily_usage_summary_user_name"), table_name="daily_usage_summary"
    )
    op.drop_index(
        op.f("ix_daily_usage_summary_user_id"), table_name="daily_usage_summary"
    )
    op.drop_index(
        op.f("ix_daily_usage_summary_tenant_name"), table_name="daily_usage_summary"
    )
    op.drop_index(
        op.f("ix_daily_usage_summary_agent_name"), table_name="daily_usage_summary"
    )
    op.drop_index(
        op.f("ix_daily_usage_summary_agent_category"), table_name="daily_usage_summary"
    )
    op.drop_column("daily_usage_summary", "total_requests")
    op.drop_column("daily_usage_summary", "agent_category")
    op.drop_column("daily_usage_summary", "agent_name")
    op.drop_column("daily_usage_summary", "user_name")
    op.drop_column("daily_usage_summary", "user_id")
    op.drop_column("daily_usage_summary", "tenant_name")
    op.drop_column("agent_configs", "allowed_sources")
    # ### end Alembic commands ###
