"""change in tenant  model for link

Revision ID: 9a8b54dd42a4
Revises: 17394a8c3c33
Create Date: 2026-02-24 10:52:24.990924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a8b54dd42a4"
down_revision: Union[str, Sequence[str], None] = "17394a8c3c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("created_by", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "created_by")
    # ### end Alembic commands ###
