"""after merge sepcilalization1

Revision ID: 9d9a237bb403
Revises: 0bbf8b9a99c8
Create Date: 2026-03-12 06:11:27.271894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9d9a237bb403"
down_revision: Union[str, Sequence[str], None] = "0bbf8b9a99c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents", "specialisation_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents", "specialisation_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
