"""update the daily uage summary for some columns

Revision ID: 9e0868cece2a
Revises: 96f12e0a1b37
Create Date: 2026-02-27 14:08:41.774714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9e0868cece2a"
down_revision: Union[str, Sequence[str], None] = "96f12e0a1b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_usage_summary",
        sa.Column("total_conversations", sa.Integer(), nullable=True),
    )
    op.add_column(
        "daily_usage_summary", sa.Column("total_messages", sa.Integer(), nullable=True)
    )
    op.add_column(
        "daily_usage_summary", sa.Column("estimated_cost", sa.Float(), nullable=True)
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("avg_conversation_length", sa.Float(), nullable=True),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("avg_response_time_ms", sa.Float(), nullable=True),
    )
    op.alter_column(
        "daily_usage_summary", "total_tokens", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("daily_usage_summary", "total_requests")
    op.drop_column("daily_usage_summary", "avg_response_time")
    op.drop_column("daily_usage_summary", "total_cost")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_usage_summary",
        sa.Column(
            "total_cost",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column(
            "avg_response_time", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "daily_usage_summary",
        sa.Column("total_requests", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "daily_usage_summary",
        "total_tokens",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("daily_usage_summary", "avg_response_time_ms")
    op.drop_column("daily_usage_summary", "avg_conversation_length")
    op.drop_column("daily_usage_summary", "estimated_cost")
    op.drop_column("daily_usage_summary", "total_messages")
    op.drop_column("daily_usage_summary", "total_conversations")
    # ### end Alembic commands ###
