"""fix for is_chant_agent for usage_log

Revision ID: b5bf475750f4
Revises: 1a9d3b7ce655
Create Date: 2026-03-05 13:27:43.822813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b5bf475750f4"
down_revision: Union[str, Sequence[str], None] = "1a9d3b7ce655"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_logs", sa.Column("is_chat_agent", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_logs", "is_chat_agent")
    # ### end Alembic commands ###
