"""created tone table and modification in agent config

Revision ID: bb4bb6100a0a
Revises: 74b10d9c28b1
Create Date: 2026-03-23 14:12:37.852787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4bb6100a0a'
down_revision: Union[str, Sequence[str], None] = '74b10d9c28b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tones_id'), 'tones', ['id'], unique=False)
    op.add_column('agent_configs', sa.Column('tone_id', sa.Integer(), nullable=True))
    op.add_column('agent_configs', sa.Column('welcome_message', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'agent_configs', 'tones', ['tone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.drop_column('agent_configs', 'welcome_message')
    op.drop_column('agent_configs', 'tone_id')
    op.drop_index(op.f('ix_tones_id'), table_name='tones')
    op.drop_table('tones')
    # ### end Alembic commands ###
