"""baseline schema

Revision ID: bf6683e8d981
Revises: 693ac99ea07a
Create Date: 2026-02-26 15:09:17.512778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf6683e8d981"
down_revision: Union[str, Sequence[str], None] = "693ac99ea07a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("data_tenants_docs_embedding_idx"),
        table_name="data_tenants_docs",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "200"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        op.f("tenants_docs_idx"), table_name="data_tenants_docs", postgresql_using="gin"
    )
    op.drop_index(op.f("tenants_docs_idx_1"), table_name="data_tenants_docs")
    op.drop_index(
        op.f("tenants_docs_idx_file_hash_text"), table_name="data_tenants_docs"
    )
    op.drop_index(
        op.f("tenants_docs_idx_tenant_id_text"), table_name="data_tenants_docs"
    )
    op.drop_table("data_tenants_docs")
    op.add_column(
        "agent_configs", sa.Column("model_name", sa.String(length=100), nullable=False)
    )
    op.add_column("agent_configs", sa.Column("temperature", sa.Float(), nullable=True))
    op.add_column("agent_configs", sa.Column("system_prompt", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_agent_configs_model_name"),
        "agent_configs",
        ["model_name"],
        unique=False,
    )
    op.create_unique_constraint(None, "agent_configs", ["agent_id"])
    op.drop_constraint(
        op.f("agent_configs_created_by_fkey"), "agent_configs", type_="foreignkey"
    )
    op.drop_column("agent_configs", "created_at")
    op.drop_column("agent_configs", "value")
    op.drop_column("agent_configs", "updated_at")
    op.drop_column("agent_configs", "created_by")
    op.drop_column("agent_configs", "key")
    op.add_column(
        "agents", sa.Column("alias_name", sa.String(length=100), nullable=True)
    )

    # Create enum type
    op.execute(
        "CREATE TYPE agent_specialisation AS ENUM ('GENERAL', 'HR', 'TECHNICAL_SUPPORT');"
    )

    op.add_column(
        "agents",
        sa.Column(
            "specialisation",
            sa.Enum("GENERAL", "HR", "TECHNICAL_SUPPORT", name="agent_specialisation"),
            nullable=False,
        ),
    )
    op.add_column("agents", sa.Column("is_template", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_agents_specialisation"), "agents", ["specialisation"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agents_specialisation"), table_name="agents")
    op.drop_column("agents", "is_template")
    op.drop_column("agents", "specialisation")
    op.drop_column("agents", "alias_name")
    op.add_column(
        "agent_configs",
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "agent_configs",
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_configs",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "agent_configs",
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "agent_configs",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("agent_configs_created_by_fkey"),
        "agent_configs",
        "users",
        ["created_by"],
        ["id"],
    )
    op.drop_constraint(None, "agent_configs", type_="unique")
    op.drop_index(op.f("ix_agent_configs_model_name"), table_name="agent_configs")
    op.drop_column("agent_configs", "system_prompt")
    op.drop_column("agent_configs", "temperature")
    op.drop_column("agent_configs", "model_name")
    op.create_table(
        "data_tenants_docs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata_",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "text_search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, (text)::text)", persisted=True
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("data_tenants_docs_pkey")),
    )
    op.create_index(
        op.f("tenants_docs_idx_tenant_id_text"),
        "data_tenants_docs",
        [sa.literal_column("((metadata_ ->> 'tenant_id'::text)::character varying)")],
        unique=False,
    )
    op.create_index(
        op.f("tenants_docs_idx_file_hash_text"),
        "data_tenants_docs",
        [sa.literal_column("((metadata_ ->> 'file_hash'::text)::character varying)")],
        unique=False,
    )
    op.create_index(
        op.f("tenants_docs_idx_1"),
        "data_tenants_docs",
        [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")],
        unique=False,
    )
    op.create_index(
        op.f("tenants_docs_idx"),
        "data_tenants_docs",
        ["text_search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("data_tenants_docs_embedding_idx"),
        "data_tenants_docs",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "200"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
