"""change in document check for processing id

Revision ID: eca83942b558
Revises: 026b575b525b
Create Date: 2026-02-24 15:30:09.830551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eca83942b558"
down_revision: Union[str, Sequence[str], None] = "026b575b525b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("processing_id", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "processing_id")
    # ### end Alembic commands ###
