"""change in tenant  model for link

Revision ID: f00fa1e5b9be
Revises: 14de38cbf92b
Create Date: 2026-02-24 10:43:32.134921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f00fa1e5b9be"
down_revision: Union[str, Sequence[str], None] = "14de38cbf92b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("created_by", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tenants", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenants", type_="foreignkey")
    op.drop_column("tenants", "created_by")
    # ### end Alembic commands ###
